<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE vehicle-configuration [
	<!ELEMENT vehicle-configuration (vehicle*, rover-name-list)>
	<!ELEMENT vehicle (description?, drivetrain-efficiency, base-speed, 
	empty-mass, crew-size?, cargo?, part-attachment?, sickbay?, lab?, 
	airlock?, activity?)>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ATTLIST vehicle width CDATA #REQUIRED>
	<!ATTLIST vehicle length CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT drivetrain-efficiency EMPTY>
	<!ATTLIST drivetrain-efficiency value CDATA #REQUIRED>
	<!ELEMENT base-speed EMPTY>
	<!ATTLIST base-speed value CDATA #REQUIRED>
	<!ELEMENT empty-mass EMPTY>
	<!ATTLIST empty-mass value CDATA #REQUIRED>
	<!ELEMENT crew-size EMPTY>
	<!ATTLIST crew-size value CDATA #REQUIRED>
	<!ELEMENT cargo (capacity*)>
	<!ATTLIST cargo total-capacity CDATA #REQUIRED>
	<!ELEMENT capacity EMPTY>
	<!ATTLIST capacity resource CDATA #REQUIRED>
	<!ATTLIST capacity value CDATA #REQUIRED>
	<!ELEMENT part-attachment (part+)>
	<!ATTLIST part-attachment number-slots CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ELEMENT sickbay EMPTY>
	<!ATTLIST sickbay tech-level CDATA #REQUIRED>
	<!ATTLIST sickbay beds CDATA #REQUIRED>
	<!ELEMENT lab (tech-specialty+)>
	<!ATTLIST lab tech-level CDATA #REQUIRED>
	<!ELEMENT tech-specialty EMPTY>
	<!ATTLIST tech-specialty value CDATA #REQUIRED>
	<!ELEMENT airlock EMPTY>
	<!ATTLIST airlock xloc CDATA #REQUIRED>
	<!ATTLIST airlock yloc CDATA #REQUIRED>
	<!ATTLIST airlock interior-xloc CDATA #REQUIRED>
	<!ATTLIST airlock interior-yloc CDATA #REQUIRED>
	<!ATTLIST airlock exterior-xloc CDATA #REQUIRED>
	<!ATTLIST airlock exterior-yloc CDATA #REQUIRED>
	<!ELEMENT activity (activity-spot+)>
	<!ELEMENT activity-spot EMPTY>
	<!ATTLIST activity-spot type CDATA #REQUIRED>
	<!ATTLIST activity-spot xloc CDATA #REQUIRED>
	<!ATTLIST activity-spot yloc CDATA #REQUIRED>
	<!ELEMENT rover-name-list (rover-name*)>
	<!ELEMENT rover-name EMPTY>
	<!ATTLIST rover-name value CDATA #REQUIRED>
]>

<!--
1. Pressurized Rover Airlocks
http://www.astrotecture.com/EVA_Systems_files/SAE-2000-01-2389.pdf

2. NASA Space Exploration Vehicle Concept
http://www.nasa.gov/pdf/464826main_SEV_Concept_FactSheet.pdf

3. Surface Mobility Technology Development: Pressurized Mars Rovers
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.121.575&rep=rep1&type=pdf

4. For methane gas, 

Specific energy is 55.5	MJ/kg, or 15,416 Wh/kg, or 15.416kWh / kg

Energy density is 0.0364 MJ/L, 36.4 kJ/L or 10 Wh/L
 
Note : 1 MJ = 0.277778 kWh; 1 kWh = 3.6 MJ
 
5. Assume Solid Oxide Fuel Cell (SOFC) has 57% efficiency. 
 https://www.sciencedaily.com/releases/2012/05/120531165720.htm
 
6. According to Zubrin, it is estimated that a 1 tonne pressurized ground rover would require about 0.5 kg of
methane/oxygen bipropellant to travel 1 km. Thus a 800 km round trip excursion would consume about 400 kg of
propellant. 
http://www.marspapers.org/paper/Zubrin_1991.pdf

 -->
 

<vehicle-configuration>

	<vehicle type="Explorer Rover" width="3.5" length="8.0">
		<!-- Note: the vehicle types used here must match those in message.properties -->
		
		<description>A rover for collecting rock samples from remote sites and ice prospecting.</description>

		<!-- The efficiency of the vehicle's drivetrain. (kWh/km) (required) -->
		<!-- Default: varied according to the type of vehicle -->
		<drivetrain-efficiency value=".15" />

		<!-- Base speed of rover (km/hr) (required) -->
		<!-- Default: varies according to the type of vehicle -->
		<base-speed value="30.0" />

		<!-- Empty mass of rover (kg) (required) -->
		<!-- Default: varies according to the type of vehicle  -->
		<empty-mass value="2000.0" />

		<!-- The crew size of an rover -->
		<!-- Default: varies according to the type of vehicle -->
		<crew-size value="4" />

		<!-- Cargo capacity list -->
		<!-- See Rover.java for adding capacity for each resource -->
		<!-- total-capacity: total cargo capacity of rover. (kg) -->
		<!-- Default: varies according to the type of vehicle -->
		<cargo total-capacity="2500.0">

			<!-- If assuming a 10 sol excursion, each person would 
      			 consume the following : -->
			<!--   Water : 30.0 kg -->
			<!--    Food :  6.2 kg -->
			<!-- Dessert :  3.0 kg -->
			<!--  Oxygen :  8.4 kg -->

			<!-- The methane cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle -->
			<!-- The H2 tank on Toyota Mirai has a 5 kg capacity http://www.mytoyotamirai.com/toyota-mirai-specifications/ -->
			<capacity resource="methane" value="180.0" />

			<!-- The oxygen cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="oxygen" value="110.0" />

			<!-- The oxygen cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="nitrogen" value="110.0" />
			
			<!-- The water cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="water" value="400.0" />

			<!-- The food cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="food" value="256.0" />

			<!-- The dessert cargo capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle -->
			<capacity resource="dessert" value="120.0" />

			<!-- The rock samples cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: varies according to the type of vehicle -->
			<!-- <capacity resource="Rock Samples" value="2000.0" /> -->

			<!-- The ice cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: varies according to the type of vehicle -->
			<!-- <capacity resource="Ice" value="2000.0" /> -->

			<!-- The food waste capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="food waste" value="40.0" />
			
			<!-- The solid waste capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="solid waste" value="80.0" />	

			<!-- The toxic waste capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="toxic waste" value="40.0" />	

			<!-- The grey water capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="grey water" value="240.0" />	

			<!-- The black water capacity of the rover (kg) -->
			<!-- Default: varies according to the type of vehicle  -->
			<capacity resource="black water" value="60.0" />	
	
		</cargo>

		<!-- Sickbay -->
		<!-- Medical tech level of sickbay (see tech_level.txt) - default: 1 -->
		<!-- Number of beds in sickbay - default: 1 -->
		<sickbay tech-level="2" beds="1" />

		<!-- Lab -->
		<!-- Science tech level of lab (see tech_level.txt) - default: 1 -->
		<lab tech-level="1">
			<!-- Science tech specialty -->
			<tech-specialty value="Areology" />
			<tech-specialty value="Biology" />
		</lab>

		<!-- Airlock locations (optional) -->
		<!-- xloc, yloc: the relative X/Y location inside the airlock. -->
		<!-- interior-xloc, interior-yloc: the relative X/Y location inside the vehicle. -->
		<!-- exterior-xloc, exterior-yloc: the relative X/Y location outside the vehicle. -->
		<airlock xloc="-1.25" yloc="0.0" interior-xloc="-.75" interior-yloc="0.0" exterior-xloc="-2.75"
		exterior-yloc="0.0" />

		<!-- Activity spots -->
		<!-- Locations for people to perform various activities within the vehicle. -->
		<activity>
			<activity-spot type="operator" xloc=".45" yloc="2.7" />
			<activity-spot type="passenger" xloc="-.45" yloc="2.7" />
			<activity-spot type="passenger" xloc=".45" yloc="1.7" />
			<activity-spot type="passenger" xloc="-.45" yloc="1.7" />
			<activity-spot type="sickbay" xloc="-.6" yloc="-.2" />
			<activity-spot type="lab" xloc=".25" yloc=".3" />
		</activity>

	</vehicle>

	<!-- Transport rover -->
	<vehicle type="Transport Rover" width="3.5" length="9.5">
		<description>A rover for transporting people from one settlement to another.</description>
		<drivetrain-efficiency value=".18" />
		<base-speed value="25.0" />
		<empty-mass value="3000.0" />
		<crew-size value="8" />
		<cargo total-capacity="3500.0">
			<capacity resource="methane" value="220.0" />
			<capacity resource="oxygen" value="176.0" />
			<capacity resource="nitrogen" value="176.0" />			
			<capacity resource="water" value="800.0" />
			<capacity resource="food" value="512.0" />
			<capacity resource="dessert" value="240.0" />

			<capacity resource="food waste" value="80.0" />
			<capacity resource="solid waste" value="160.0" />
			<capacity resource="toxic waste" value="80.0" />	
			
			<capacity resource="grey water" value="480.0" />
			<capacity resource="black water" value="120.0" />
			
		</cargo>
		<sickbay tech-level="3" beds="2" />
		<airlock xloc="-1.25" yloc="0.0" interior-xloc="-.75" interior-yloc="0.0" exterior-xloc="-2.75"
		exterior-yloc="0.0" />
		<activity>
			<activity-spot type="operator" xloc=".45" yloc="4.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="4.3" />
			<activity-spot type="passenger" xloc=".45" yloc="3.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="3.3" />
			<activity-spot type="passenger" xloc=".45" yloc="2.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="2.3" />
			<activity-spot type="passenger" xloc=".45" yloc="1.3" />
			<activity-spot type="passenger" xloc="-.45" yloc="1.3" />
			<activity-spot type="sickbay" xloc="0.0" yloc=".3" />
		</activity>
	</vehicle>

	<!-- Cargo rover -->
	<vehicle type="Cargo Rover" width="4.0" length="8.0">
		<description>A rover for transporting cargo from one settlement to another.</description>
		<drivetrain-efficiency value=".2" />
		<base-speed value="25.0" />
		<empty-mass value="2500.0" />
		<crew-size value="2" />
		<cargo total-capacity="5000.0">
			<capacity resource="methane" value="260.0" />
			<capacity resource="oxygen" value="66.0" />
			<capacity resource="nitrogen" value="66.0" />		
			<capacity resource="water" value="200.0" />
			<capacity resource="food" value="128.0" />
			<capacity resource="dessert" value="60" />

			<capacity resource="food waste" value="20.0" />
			<capacity resource="solid waste" value="40.0" />
			<capacity resource="toxic waste" value="20.0" />	
			
			<capacity resource="grey water" value="120.0" />
			<capacity resource="black water" value="30.0" />
		</cargo>
		<sickbay tech-level="1" beds="1" />
		<airlock xloc="-1.5" yloc="0.0" interior-xloc="-1.0" interior-yloc="0.0" exterior-xloc="-3.0"
		exterior-yloc="0.0" />
		<activity>
			<activity-spot type="operator" xloc=".5" yloc="2.9" />
			<activity-spot type="passenger" xloc="-.5" yloc="2.9" />
			<activity-spot type="sickbay" xloc="0.0" yloc="1.9" />
		</activity>
	</vehicle>

	<!-- Light Utility Vehicle -->
	<vehicle type="Light Utility Vehicle" width="1.7" length="2.55">
		<description>A small, unpressurized, one crew utility vehicle with attachable parts.</description>
		<drivetrain-efficiency value=".35" />
		<base-speed value="30.0" />
		<empty-mass value="300.0" />
		<crew-size value="1" />
		<part-attachment number-slots="2">
            <part name="bulldozer blade" />
			<part name="pneumatic drill" />
			<part name="backhoe" />
			<part name="soil compactor" />
			<part name="drilling rig" />
			<part name="crane boom" />
		</part-attachment>
		<activity>
			<activity-spot type="operator" xloc="0.0" yloc=".13" />
		</activity>
	</vehicle>

	<!-- remote controlled prospecting rover
	<vehicle type="remote controlled prospector" width="1.5" length="2.5">
		<description>used for automatic mineral prospecting</description>
		<drivetrain-efficiency value="1.0" />
		<base-speed value="12.0" />
		<empty-mass value="250.0" />
		<crew-size value="0" />
		<cargo total-capacity="500.0">
			<capacity resource="methane" value="100.0" />
		</cargo>
	</vehicle>-->
<!--
	<vehicle type="rc dirigible" width="5.0" length="15.0">
		<description>
			remote controlled lighter-than-air craft for use
			in atmospheric research or as communications relay.
			can only function in a certain range of temperature
			and air pressure.
		</description>
	</vehicle>
-->
	<!-- low mars orbit atmosphere space craft
	<vehicle type="sounding rocket" width="0.5" length="3.0" >
		<description>
			a small rocket for atmospheric research
			or for delivering payloads to surface
			locations by hard landing
		</description>
		<drivetrain-efficiency value="1.0"/>
		<base-speed value="10.0" />
		<empty-mass value="200.0"/>
		<crew-size value="0"/>
		<cargo total-capacity="500.0">
			<capacity resource="oxygen" value="150"/>
			<capacity resource="hydrogen" value="150.0"/>
		</cargo>
		<part-attachment number-slots="1">
			<part name="satellite dish"/>
			<part name="algae tank"/>
		</part-attachment>
	</vehicle>
-->
	<!-- List of rover names -->
	<rover-name-list>
		<rover-name value="Agartha" /> <!-- Agartha is a legendary city that is said to be located in the Earth's core -->
		<rover-name value="Agni" /> <!-- Hindi for "fire" -->
		<rover-name value="Angaraka" /> <!-- Mars in Jyotish astrology (alternate name) -->
		<rover-name value="Areos Aster" /> <!-- Greek for "star of Ares" -->
		<rover-name value="Atlanta" /> <!-- The meaning of Atlanta is secure, immovable -->
		<rover-name value="al-Mirrikh" /> <!-- Arabic/Persian for "Mars" -->
		<rover-name value="Bahram" /> <!-- Ancient Persian for "Mars" -->
		<rover-name value="Beagle IV" />
		<rover-name value="Bedouin" />		
		<rover-name value="Blodstjarna" /> <!-- Viking for "Mars" (not certain) -->
		<rover-name value="Crater Crab" />		
		<rover-name value="Desert Fox" />
		<rover-name value="Desert Pearl" />	
		<rover-name value="Desert Rose" />
		<rover-name value="Deimos Tide" />
		<rover-name value="Desert Star" />
		<rover-name value="Drift Wood" />
		<rover-name value="Desertfarer" />
		<rover-name value="Dream Chaser" />	
		<rover-name value="Dune Drifter" />
		<rover-name value="Dune Runner" />
		<rover-name value="Dusty Star" />
		<rover-name value="Dust Storm" />
		<rover-name value="Dust Sprite" />
		<rover-name value="Firefly" />
		<rover-name value="Fire Star" />	
		<rover-name value="Fremen Wanderer" />			
		<rover-name value="Gypsea" />
		<rover-name value="Huoxing" /> <!-- Chinese for "Mars" -->		
		<rover-name value="Martian Escape" />		
		<rover-name value="Martian Cloud" />
		<rover-name value="Mangala" /> <!--  Sanskrit for "Mars" in Jyotish astrology -->
		<rover-name value="Ma'adim" /> <!-- Hebrew for "Mars" -->
		<rover-name value="Merih" /> <!-- Turkish for "Mars" -->	
		<rover-name value="Naag" /> <!-- Hindi for "snake" -->			
		<rover-name value="Nomad" />		
		<rover-name value="Oasis" />	
		<rover-name value="Osprey" />			
		<rover-name value="Opportunity II" />
		<rover-name value="Odyssey" />
		<rover-name value="Phobos Drifter" />
		<rover-name value="Serenity" />
		<rover-name value="Princess of the Sands" />
		<rover-name value="Red Mariner" />
		<rover-name value="Red Moon" />
		<rover-name value="Ridge Runner" />		
		<rover-name value="Shooting Star" />
		<rover-name value="Sand Dancer" />
		<rover-name value="Spice Trader" />
		<rover-name value="Solitude" />
		<rover-name value="Sand Spirit" />		
		<rover-name value="Sand Crawler" />
		<rover-name value="Sojourner II" />
		<rover-name value="Spirit II" />
		<rover-name value="Sun Dancer" />
		<rover-name value="Rahu" /> <!-- Hindi for "Mars" (not certain) -->
		<rover-name value="Vayu" /> <!-- Hindi for "wind" -->
		<rover-name value="Prithvi" /> <!-- Hindi for "earth" -->
		<rover-name value="Reth" /> <!-- Hindi for "sand" -->
		<rover-name value="Sakit" /> <!-- Ancient Turkish for "Mars" -->
		<rover-name value="Nergal" /> <!-- Babylonian for "Mars" -->
		<rover-name value="Vikram" /> <!-- a male Hindu/Sanskrit name for being valorous, wise, brave and strong as well as victorious-->
		<rover-name value="Wind Runner" />
		<rover-name value="Windstorm" />

	</rover-name-list>

</vehicle-configuration>